<h1>
    Sulfate
</h1>

In [1]:
import numpy as np
import math
from math import prod

#filename of molecule
filename = 'sulfate.xyz'

#atomic mass unit (kg)
amu = 1.66053886e-27

#Planck constant (Js)
planck = 6.62606957e-34

#Angstrom
Ao = 1e-10

#temperature (Kelvin), wasn't given a specific value so I set it to one :)
T = 1

#Boltzmann Constant
Kb = 1.38e-23

#Gas constant R
R = 8.31

#symmetry number sigma (for sulfate, changes depending on molecule)
symmetry_number_sigma = 12

#number of atoms in molecule
No_of_Atoms = []

#respective coordinates
x_coordinates= []
y_coordinates= []
z_coordinates= []

#opening the file
file_open = open(filename)

#reading the number of atoms from the file
N_Atoms = int(file_open.readline())

#reading the title for the molecules name
title = file_open.readline()

#loops through the file 
for i in file_open:

    #splits the file into atom,x,y,z to get respective information
    atom,x,y,z = i.split()
    No_of_Atoms.append(atom)

    x_coordinates.append(Ao*(float(x)))
    y_coordinates.append(Ao*(float(y)))
    z_coordinates.append(Ao*(float(z)))

file_open.close()

print("Molecule:  %s" % title)
print('\n')

#%d used to specify integers
print("number of atoms:  %d" % N_Atoms)
print('\n')
print("x-coordinates:  %s" % x_coordinates)
print('\n')
print("y-coordinates:  %s" % y_coordinates)
print('\n')
print("z-coordinates:  %s" % z_coordinates)
print('\n')

#mass of molecule
mass = N_Atoms*amu
print(mass)

#coordinate values squared
x_squared = [xo ** 2 for xo in x_coordinates]
y_squared = [yo ** 2 for yo in y_coordinates]
z_squared = [zo ** 2 for zo in z_coordinates]

#product of two lists of coordinates
xy = []
yz = []
xz = []

for x1, y2 in zip(x_coordinates, y_coordinates):
    xy.append(x1 * y2)

for y22, z1 in zip(y_coordinates, z_coordinates):
    yz.append(y22 * z1)

for x11, z22 in zip(x_coordinates, z_coordinates):
    xz.append(x11 * z22)

#inertia matrix elements
Ixx = mass * np.sum((y_squared + z_squared))
Iyy = mass * np.sum((x_squared + z_squared))
Izz = mass * np.sum((x_squared + y_squared))
Ixy = -mass * np.sum(xy)
Iyz = -mass * np.sum(yz)
Ixz = -mass * np.sum(xz)

#inertia matrix
I = np.array([[Ixx, Ixy, Ixz], [Ixy, Iyy, Iyz], [Ixz, Iyz, Izz]])
print('\n')
print(I)
print('\n')

#principle moments of inertia, eigenvalues of the inertia materix
principle = np.linalg.eigvals(I)
print(principle)
print('\n')

#constants of rotational entropy equation
c1 = ((np.pi)**0.5)/symmetry_number_sigma
c2 = np.sqrt((8*((np.pi)**2)*Kb*T)/(planck**2))

#square rooting all eigenvalues (its how I've manipulated the equation)
eigen_rooted = []
for i in principle:
    eigen_rooted.append(np.sqrt(i))

#rotational entropy
S = R*np.log(c1*c2*math.prod(eigen_rooted))
print(f"Rotational Entropy = {S:.2f} per unit mass")
print('\n')
print("note: per unit mass has units J K^-1 Kg^-1")

Molecule:  sulfate



number of atoms:  5


x-coordinates:  [1.692792e-10, 3.440443e-10, 1.261757e-10, 1.6144220000000002e-10, 2.014109e-10]


y-coordinates:  [1.121477e-09, 9.57022e-10, 8.97606e-10, 9.35802e-10, 9.77181e-10]


z-coordinates:  [4.308174e-10, 4.2485039999999996e-10, 3.478761e-10, 5.829759e-10, 4.47525e-10]


8.3026943e-27


[[ 4.84641982e-44 -8.13871274e-45 -3.71331874e-45]
 [-8.13871274e-45  1.04350833e-44 -1.81402379e-44]
 [-3.71331874e-45 -1.81402379e-44  4.18412499e-44]]


[4.77650106e-46 5.01367466e-44 5.01261347e-44]


Rotational Entropy = -843.71 per unit mass


note: per unit mass has units J K^-1 Kg^-1


<h1>
    Adamantane
</h1>

In [2]:
import numpy as np
import math
from math import prod

filename = 'adamantane.xyz'

amu = 1.66053886e-27
planck = 6.62606957e-34
Ao = 1e-10
T = 1
Kb = 1.38e-23
R = 8.31
symmetry_number_sigma = 12

No_of_Atoms = []
x_coordinates= []
y_coordinates= []
z_coordinates= []

file_open = open(filename)
N_Atoms = int(file_open.readline())
title = file_open.readline()

for i in file_open:
    atom,x,y,z = i.split()
    No_of_Atoms.append(atom)
    x_coordinates.append(Ao*(float(x)))
    y_coordinates.append(Ao*(float(y)))
    z_coordinates.append(Ao*(float(z)))
file_open.close()

print("Molecule:  %s" % title)
print('\n')
print("number of atoms:  %d" % N_Atoms)
print('\n')
print("x-coordinates:  %s" % x_coordinates)
print('\n')
print("y-coordinates:  %s" % y_coordinates)
print('\n')
print("z-coordinates:  %s" % z_coordinates)
print('\n')

mass = N_Atoms*amu
print(mass)

x_squared = [xo ** 2 for xo in x_coordinates]
y_squared = [yo ** 2 for yo in y_coordinates]
z_squared = [zo ** 2 for zo in z_coordinates]

xy = []
yz = []
xz = []

for x1, y2 in zip(x_coordinates, y_coordinates):
    xy.append(x1 * y2)

for y22, z1 in zip(y_coordinates, z_coordinates):
    yz.append(y22 * z1)

for x11, z22 in zip(x_coordinates, z_coordinates):
    xz.append(x11 * z22)

Ixx = mass * np.sum((y_squared + z_squared))
Iyy = mass * np.sum((x_squared + z_squared))
Izz = mass * np.sum((x_squared + y_squared))
Ixy = -mass * np.sum(xy)
Iyz = -mass * np.sum(yz)
Ixz = -mass * np.sum(xz)

I = np.array([[Ixx, Ixy, Ixz], [Ixy, Iyy, Iyz], [Ixz, Iyz, Izz]])
print('\n')
print(I)
print('\n')

principle = np.linalg.eigvals(I)
print(principle)
print('\n')

c1 = ((np.pi)**0.5)/symmetry_number_sigma
c2 = np.sqrt((8*((np.pi)**2)*Kb*T)/(planck**2))

eigen_rooted = []
for i in principle:
    eigen_rooted.append(np.sqrt(i))

S = R*np.log(c1*c2*math.prod(eigen_rooted))
print(f"Rotational Entropy = {S:.2f} per unit mass")
print('\n')
print("note: per unit mass has units J K^-1 Kg^-1")

Molecule:  adamantane



number of atoms:  26


x-coordinates:  [1.19658e-09, 1.4434200000000002e-09, 1.3395361e-09, 1.3004640000000001e-09, 1.21572e-09, 1.4242800000000002e-09, 1.4643419000000001e-09, 1.175658e-09, 1.32e-09, 1.32e-09, 1.11078e-09, 1.5292199e-09, 1.3556399e-09, 1.28436e-09, 1.33122e-09, 1.3087800000000001e-09, 1.22694e-09, 1.41306e-09, 1.4764200000000002e-09, 1.16358e-09, 1.1286e-09, 1.5114000000000002e-09, 1.23486e-09, 1.4051399000000001e-09, 1.55364e-09, 1.08636e-09]


y-coordinates:  [1.3004640000000001e-09, 1.3395361e-09, 1.19658e-09, 1.4434200000000002e-09, 1.175658e-09, 1.4643419000000001e-09, 1.21572e-09, 1.4242800000000002e-09, 1.32e-09, 1.32e-09, 1.28436e-09, 1.3556399e-09, 1.11078e-09, 1.5292199e-09, 1.22694e-09, 1.41306e-09, 1.3087800000000001e-09, 1.33122e-09, 1.1286e-09, 1.5114000000000002e-09, 1.16358e-09, 1.4764200000000002e-09, 1.08636e-09, 1.55364e-09, 1.23486e-09, 1.4051399000000001e-09]


z-coordinates:  [1.6747811e-09, 1.6747811e-09, 1.8492190999999

<h1>
    Ammonium
</h1>

In [3]:
import numpy as np
import math
from math import prod

filename = 'ammonium.xyz'

amu = 1.66053886e-27
planck = 6.62606957e-34
Ao = 1e-10
T = 1
Kb = 1.38e-23
R = 8.31
symmetry_number_sigma = 12

No_of_Atoms = []
x_coordinates= []
y_coordinates= []
z_coordinates= []

file_open = open(filename)
N_Atoms = int(file_open.readline())
title = file_open.readline()

for i in file_open:
    atom,x,y,z = i.split()
    No_of_Atoms.append(atom)
    x_coordinates.append(Ao*(float(x)))
    y_coordinates.append(Ao*(float(y)))
    z_coordinates.append(Ao*(float(z)))
file_open.close()

print("Molecule:  %s" % title)
print('\n')
print("number of atoms:  %d" % N_Atoms)
print('\n')
print("x-coordinates:  %s" % x_coordinates)
print('\n')
print("y-coordinates:  %s" % y_coordinates)
print('\n')
print("z-coordinates:  %s" % z_coordinates)
print('\n')

mass = N_Atoms*amu
print(mass)

x_squared = [xo ** 2 for xo in x_coordinates]
y_squared = [yo ** 2 for yo in y_coordinates]
z_squared = [zo ** 2 for zo in z_coordinates]

xy = []
yz = []
xz = []

for x1, y2 in zip(x_coordinates, y_coordinates):
    xy.append(x1 * y2)

for y22, z1 in zip(y_coordinates, z_coordinates):
    yz.append(y22 * z1)

for x11, z22 in zip(x_coordinates, z_coordinates):
    xz.append(x11 * z22)

Ixx = mass * np.sum((y_squared + z_squared))
Iyy = mass * np.sum((x_squared + z_squared))
Izz = mass * np.sum((x_squared + y_squared))
Ixy = -mass * np.sum(xy)
Iyz = -mass * np.sum(yz)
Ixz = -mass * np.sum(xz)

I = np.array([[Ixx, Ixy, Ixz], [Ixy, Iyy, Iyz], [Ixz, Iyz, Izz]])
print('\n')
print(I)
print('\n')

principle = np.linalg.eigvals(I)
print(principle)
print('\n')

c1 = ((np.pi)**0.5)/symmetry_number_sigma
c2 = np.sqrt((8*((np.pi)**2)*Kb*T)/(planck**2))

eigen_rooted = []
for i in principle:
    eigen_rooted.append(np.sqrt(i))

S = R*np.log(c1*c2*math.prod(eigen_rooted))
print(f"Rotational Entropy = {S:.2f} per unit mass")
print('\n')
print("note: per unit mass has units J K^-1 Kg^-1")

Molecule:  ammonium



number of atoms:  5


x-coordinates:  [2.123827e-10, 5.0156800000000005e-11, 1.496867e-10, 1.426334e-10, 1.41693e-10]


y-coordinates:  [1.235004e-09, 1.20954e-09, 1.08222e-09, 1.154368e-09, 1.1715562e-09]


z-coordinates:  [7.172334000000001e-10, 7.196202000000001e-10, 6.903819e-10, 8.401536e-10, 7.428915000000001e-10]


8.3026943e-27


[[ 7.99647552e-44 -6.77173414e-45 -4.29132469e-45]
 [-6.77173414e-45  2.38876770e-44 -3.60629703e-44]
 [-4.29132469e-45 -3.60629703e-44  5.79111337e-44]]


[2.19430787e-46 8.07701354e-44 8.07739997e-44]


Rotational Entropy = -842.98 per unit mass


note: per unit mass has units J K^-1 Kg^-1


<h1>
    Quinuclidinium
</h1>

In [4]:
import numpy as np
import math
from math import prod

filename = 'quinuclidinium.xyz'

amu = 1.66053886e-27
planck = 6.62606957e-34
Ao = 1e-10
T = 1
Kb = 1.38e-23
R = 8.31
symmetry_number_sigma = 3

No_of_Atoms = []
x_coordinates= []
y_coordinates= []
z_coordinates= []

file_open = open(filename)
N_Atoms = int(file_open.readline())
title = file_open.readline()

for i in file_open:
    atom,x,y,z = i.split()
    No_of_Atoms.append(atom)
    x_coordinates.append(Ao*(float(x)))
    y_coordinates.append(Ao*(float(y)))
    z_coordinates.append(Ao*(float(z)))
file_open.close()

print("Molecule:  %s" % title)
print('\n')
print("number of atoms:  %d" % N_Atoms)
print('\n')
print("x-coordinates:  %s" % x_coordinates)
print('\n')
print("y-coordinates:  %s" % y_coordinates)
print('\n')
print("z-coordinates:  %s" % z_coordinates)
print('\n')

mass = N_Atoms*amu
print(mass)

x_squared = [xo ** 2 for xo in x_coordinates]
y_squared = [yo ** 2 for yo in y_coordinates]
z_squared = [zo ** 2 for zo in z_coordinates]

xy = []
yz = []
xz = []

for x1, y2 in zip(x_coordinates, y_coordinates):
    xy.append(x1 * y2)

for y22, z1 in zip(y_coordinates, z_coordinates):
    yz.append(y22 * z1)

for x11, z22 in zip(x_coordinates, z_coordinates):
    xz.append(x11 * z22)

Ixx = mass * np.sum((y_squared + z_squared))
Iyy = mass * np.sum((x_squared + z_squared))
Izz = mass * np.sum((x_squared + y_squared))
Ixy = -mass * np.sum(xy)
Iyz = -mass * np.sum(yz)
Ixz = -mass * np.sum(xz)

I = np.array([[Ixx, Ixy, Ixz], [Ixy, Iyy, Iyz], [Ixz, Iyz, Izz]])
print('\n')
print(I)
print('\n')

principle = np.linalg.eigvals(I)
print(principle)
print('\n')

c1 = ((np.pi)**0.5)/symmetry_number_sigma
c2 = np.sqrt((8*((np.pi)**2)*Kb*T)/(planck**2))

eigen_rooted = []
for i in principle:
    eigen_rooted.append(np.sqrt(i))

S = R*np.log(c1*c2*math.prod(eigen_rooted))
print(f"Rotational Entropy = {S:.2f} per unit mass")
print('\n')
print("note: per unit mass has units J K^-1 Kg^-1")

Molecule:  quinuclidinium



number of atoms:  22


x-coordinates:  [4.5495e-10, 4.5495e-10, 4.5495e-10, 3.357531e-10, 5.741469000000001e-10, 3.2756400000000004e-10, 5.82336e-10, 3.766986e-10, 5.332014e-10, 4.5495e-10, 3.7678960000000003e-10, 5.331104e-10, 4.5495e-10, 2.7478980000000003e-10, 6.351102000000001e-10, 3.1036690000000003e-10, 5.995331000000001e-10, 3.343883e-10, 5.755118000000001e-10, 2.462189e-10, 6.636811e-10, 4.5495e-10]


y-coordinates:  [1.326921e-10, 1.326921e-10, 2.744727e-10, 3.465748e-10, 3.465748e-10, 3.4051580000000004e-10, 3.4051580000000004e-10, 8.87644e-11, 8.87644e-11, 2.8628779999999997e-10, 8.66437e-11, 8.66437e-11, 2.6368770000000004e-10, 2.7519980000000003e-10, 2.7519980000000003e-10, 4.261295e-10, 4.261295e-10, 4.351574e-10, 4.351574e-10, 3.093725e-10, 3.093725e-10, 2.750786e-10]


z-coordinates:  [5.446056e-10, 3.9196080000000006e-10, 3.43728e-10, 3.9140640000000004e-10, 3.9140640000000004e-10, 5.422032e-10, 5.422032e-10, 5.794404e-10, 5.794404e-10, 6.8